package com.safenet.dns;

import android.content.Context;
import android.net.ConnectivityManager;
import android.net.Network;
import android.net.NetworkCapabilities;

import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * User-space proxy for Internet Share.
 *
 * <p>This deliberately uses explicit HTTP and SOCKS endpoints instead of
 * VpnService. Android's VpnService captures traffic generated by the phone;
 * it does not turn a Wi-Fi Direct group into a routed NAT interface for
 * packets generated by another device. Each accepted client connection is
 * therefore opened on the active non-VPN Wi-Fi or cellular network.</p>
 */
final class TetherShareProxy {
    static final int HTTP_PORT = 8228;
    static final int SOCKS_PORT = 8229;
    static final String PROXY_HOST = "192.168.49.1";

    interface ErrorListener {
        void onError(String message);
    }

    private static final int SOCKET_TIMEOUT_MS = 15_000;
    private static final int CONNECT_TIMEOUT_MS = 10_000;
    private static final int MAX_HEADER_BYTES = 16 * 1024;
    private static final int MAX_BODY_BYTES = 32 * 1024 * 1024;
    private static final int MAX_SOCKS_HOST_BYTES = 255;

    private final Context context;
    private final ExecutorService executor = Executors.newCachedThreadPool();
    private final Set<Socket> clientSockets = ConcurrentHashMap.newKeySet();
    private final ErrorListener errorListener;
    private volatile ServerSocket httpServer;
    private volatile ServerSocket socksServer;

    TetherShareProxy(Context context, ErrorListener errorListener) {
        this.context = context;
        this.errorListener = errorListener;
    }

    synchronized void start() throws IOException {
        if (httpServer != null || socksServer != null) {
            return;
        }
        ServerSocket nextHttp = null;
        ServerSocket nextSocks = null;
        try {
            // Bind wildcard rather than the P2P address. Some Android versions
            // expose the group-owner address only after the group is created.
            nextHttp = new ServerSocket(HTTP_PORT);
            nextSocks = new ServerSocket(SOCKS_PORT);
            httpServer = nextHttp;
            socksServer = nextSocks;
            acceptLoop(nextHttp, false);
            acceptLoop(nextSocks, true);
        } catch (IOException error) {
            closeServer(nextHttp);
            closeServer(nextSocks);
            httpServer = null;
            socksServer = null;
            throw error;
        }
    }

    synchronized void stop() {
        closeServer(httpServer);
        closeServer(socksServer);
        httpServer = null;
        socksServer = null;
        for (Socket socket : clientSockets) {
            closeSocket(socket);
        }
        clientSockets.clear();
    }

    boolean isRunning() {
        ServerSocket http = httpServer;
        ServerSocket socks = socksServer;
        return http != null && !http.isClosed() && socks != null && !socks.isClosed();
    }

    private void acceptLoop(ServerSocket server, boolean socks) {
        executor.execute(() -> {
            while (isCurrentServer(server)) {
                try {
                    Socket client = server.accept();
                    clientSockets.add(client);
                    executor.execute(() -> {
                        try {
                            if (socks) {
                                handleSocksClient(client);
                            } else {
                                handleHttpClient(client);
                            }
                        } finally {
                            clientSockets.remove(client);
                            closeSocket(client);
                        }
                    });
                } catch (IOException error) {
                    if (isCurrentServer(server)) {
                        errorListener.onError(
                            "The SafeNet " + (socks ? "SOCKS" : "HTTP") + " proxy stopped unexpectedly."
                        );
                    }
                    return;
                }
            }
        });
    }

    private boolean isCurrentServer(ServerSocket server) {
        return server != null && !server.isClosed() &&
            (server == httpServer || server == socksServer);
    }

    private void handleHttpClient(Socket client) {
        try {
            client.setSoTimeout(SOCKET_TIMEOUT_MS);
            InputStream input = client.getInputStream();
            String requestLine = readLine(input);
            if (requestLine == null || requestLine.trim().isEmpty()) {
                return;
            }
            String[] requestParts = requestLine.split(" ", 3);
            if (requestParts.length != 3 || requestParts[0].trim().isEmpty()) {
                writeHttpError(client, "400 Bad Request");
                return;
            }

            String method = requestParts[0].trim();
            String target = requestParts[1].trim();
            String version = requestParts[2].trim();
            if (!version.startsWith("HTTP/")) {
                writeHttpError(client, "400 Bad Request");
                return;
            }

            List<Header> headers = new ArrayList<>();
            String hostHeader = null;
            int contentLength = 0;
            String line;
            while ((line = readLine(input)) != null && !line.isEmpty()) {
                int separator = line.indexOf(':');
                if (separator <= 0) {
                    writeHttpError(client, "400 Bad Request");
                    return;
                }
                String name = line.substring(0, separator).trim();
                String value = line.substring(separator + 1).trim();
                if (name.isEmpty()) {
                    writeHttpError(client, "400 Bad Request");
                    return;
                }
                headers.add(new Header(name, value));
                if ("Host".equalsIgnoreCase(name)) {
                    hostHeader = value;
                } else if ("Content-Length".equalsIgnoreCase(name)) {
                    try {
                        contentLength = Integer.parseInt(value);
                    } catch (NumberFormatException error) {
                        writeHttpError(client, "400 Invalid Content-Length");
                        return;
                    }
                    if (contentLength < 0 || contentLength > MAX_BODY_BYTES) {
                        writeHttpError(client, "413 Request Entity Too Large");
                        return;
                    }
                }
            }
            if (line == null) {
                writeHttpError(client, "400 Bad Request");
                return;
            }

            if ("CONNECT".equalsIgnoreCase(method)) {
                HostPort destination = parseHostPort(target, 443);
                if (!isValidDestination(destination)) {
                    writeHttpError(client, "403 Forbidden");
                    return;
                }
                Socket upstream = openUpstream(destination.host, destination.port);
                try {
                    OutputStream output = client.getOutputStream();
                    output.write((
                        "HTTP/1.1 200 Connection Established\r\n" +
                        "Proxy-Agent: SafeNet Internet Share\r\n\r\n"
                    ).getBytes(StandardCharsets.ISO_8859_1));
                    output.flush();
                    relay(client, upstream);
                } finally {
                    closeSocket(upstream);
                }
                return;
            }

            HostPort destination = resolveHttpDestination(target, hostHeader);
            if (!isValidDestination(destination)) {
                writeHttpError(client, "403 Forbidden");
                return;
            }

            Socket upstream = openUpstream(destination.host, destination.port);
            try {
                BufferedWriter writer = new BufferedWriter(
                    new OutputStreamWriter(upstream.getOutputStream(), StandardCharsets.ISO_8859_1)
                );
                URI targetUri = toHttpUri(target, hostHeader);
                String path = targetUri.getRawPath();
                if (path == null || path.isEmpty()) {
                    path = "/";
                }
                if (targetUri.getRawQuery() != null) {
                    path += "?" + targetUri.getRawQuery();
                }
                writer.write(method + " " + path + " " + version + "\r\n");
                boolean wroteHost = false;
                for (Header header : headers) {
                    if ("Proxy-Connection".equalsIgnoreCase(header.name) ||
                        "Connection".equalsIgnoreCase(header.name) ||
                        "Keep-Alive".equalsIgnoreCase(header.name) ||
                        "Transfer-Encoding".equalsIgnoreCase(header.name) ||
                        "Proxy-Authenticate".equalsIgnoreCase(header.name) ||
                        "Proxy-Authorization".equalsIgnoreCase(header.name)) {
                        continue;
                    }
                    if ("Host".equalsIgnoreCase(header.name)) {
                        writer.write("Host: " + formatHostPort(destination) + "\r\n");
                        wroteHost = true;
                    } else {
                        writer.write(header.name + ": " + header.value + "\r\n");
                    }
                }
                if (!wroteHost) {
                    writer.write("Host: " + formatHostPort(destination) + "\r\n");
                }
                writer.write("Connection: close\r\n\r\n");
                writer.flush();
                copyExactly(input, upstream.getOutputStream(), contentLength);
                upstream.getOutputStream().flush();
                relay(client, upstream);
            } finally {
                closeSocket(upstream);
            }
        } catch (HttpProxyException error) {
            try {
                writeHttpError(client, error.status);
            } catch (IOException ignored) {
                // The client may already have disconnected.
            }
        } catch (Exception error) {
            try {
                writeHttpError(client, "502 Bad Gateway");
            } catch (IOException ignored) {
                // The client may already have disconnected.
            }
        }
    }

    private void handleSocksClient(Socket client) {
        try {
            client.setSoTimeout(SOCKET_TIMEOUT_MS);
            InputStream input = client.getInputStream();
            int version = readByte(input);
            if (version == 5) {
                handleSocks5(client, input);
            } else if (version == 4) {
                handleSocks4(client, input);
            } else {
                closeSocket(client);
            }
        } catch (Exception error) {
            closeSocket(client);
        }
    }

    private void handleSocks5(Socket client, InputStream input) throws IOException {
        int methodCount = readByte(input);
        if (methodCount < 0 || methodCount > 255) {
            return;
        }
        byte[] methods = readBytes(input, methodCount);
        boolean noAuth = false;
        for (byte method : methods) {
            if ((method & 0xff) == 0) {
                noAuth = true;
                break;
            }
        }
        OutputStream output = client.getOutputStream();
        output.write(new byte[] { 5, (byte) (noAuth ? 0 : 0xff) });
        output.flush();
        if (!noAuth) {
            return;
        }

        if (readByte(input) != 5 || readByte(input) != 1 || readByte(input) != 0) {
            writeSocks5Failure(output, 0x07, 0x01);
            return;
        }
        int addressType = readByte(input);
        String host;
        if (addressType == 1) {
            host = InetAddress.getByAddress(readBytes(input, 4)).getHostAddress();
        } else if (addressType == 3) {
            int length = readByte(input);
            if (length < 1 || length > MAX_SOCKS_HOST_BYTES) {
                writeSocks5Failure(output, 0x08, addressType);
                return;
            }
            host = new String(readBytes(input, length), StandardCharsets.ISO_8859_1);
        } else if (addressType == 4) {
            host = InetAddress.getByAddress(readBytes(input, 16)).getHostAddress();
        } else {
            writeSocks5Failure(output, 0x08, addressType);
            return;
        }
        int port = readUnsignedShort(input);
        openSocksAndRelay(client, output, host, port, addressType, false);
    }

    private void handleSocks4(Socket client, InputStream input) throws IOException {
        int command = readByte(input);
        int port = readUnsignedShort(input);
        byte[] address = readBytes(input, 4);
        readNullTerminated(input, MAX_HEADER_BYTES);
        String host;
        if ((address[0] & 0xff) == 0 && (address[1] & 0xff) == 0 &&
            (address[2] & 0xff) == 0 && (address[3] & 0xff) != 0) {
            host = readNullTerminated(input, MAX_SOCKS_HOST_BYTES);
        } else {
            host = InetAddress.getByAddress(address).getHostAddress();
        }
        OutputStream output = client.getOutputStream();
        if (command != 1) {
            writeSocks4Failure(output);
            return;
        }
        openSocksAndRelay(client, output, host, port, 1, true);
    }

    private void openSocksAndRelay(
        Socket client,
        OutputStream output,
        String host,
        int port,
        int addressType,
        boolean socks4
    ) throws IOException {
        HostPort destination = new HostPort(host, port);
        if (!isValidDestination(destination)) {
            if (socks4) {
                writeSocks4Failure(output);
            } else {
                writeSocks5Failure(output, 0x02, addressType);
            }
            return;
        }

        Socket upstream;
        try {
            upstream = openUpstream(host, port);
        } catch (IOException error) {
            if (socks4) {
                writeSocks4Failure(output);
            } else {
                writeSocks5Failure(output, 0x05, addressType);
            }
            return;
        }
        try {
            if (socks4) {
                output.write(new byte[] { 0, 90, 0, 0, 0, 0, 0, 0 });
            } else {
                output.write(new byte[] { 5, 0, 0, 1, 0, 0, 0, 0, 0, 0 });
            }
            output.flush();
            relay(client, upstream);
        } finally {
            closeSocket(upstream);
        }
    }

    private void writeSocks5Failure(OutputStream output, int status, int addressType)
        throws IOException {
        int type = addressType == 1 || addressType == 4 ? addressType : 1;
        output.write(new byte[] { 5, (byte) status, 0, (byte) type, 0, 0, 0, 0, 0, 0 });
        output.flush();
    }

    private void writeSocks4Failure(OutputStream output) throws IOException {
        output.write(new byte[] { 0, 91, 0, 0, 0, 0, 0, 0 });
        output.flush();
    }

    private HostPort resolveHttpDestination(String target, String hostHeader) {
        if (target.startsWith("http://") || target.startsWith("https://")) {
            URI uri = toHttpUri(target, hostHeader);
            int defaultPort = "https".equalsIgnoreCase(uri.getScheme()) ? 443 : 80;
            return new HostPort(uri.getHost(), uri.getPort() > 0 ? uri.getPort() : defaultPort);
        }
        if (hostHeader == null || hostHeader.trim().isEmpty()) {
            throw new HttpProxyException("400 Host Required");
        }
        return parseHostPort(hostHeader, 80);
    }

    private URI toHttpUri(String target, String hostHeader) {
        try {
            if (target.startsWith("http://") || target.startsWith("https://")) {
                return URI.create(target);
            }
            return URI.create("http://" + hostHeader + (target.startsWith("/") ? target : "/" + target));
        } catch (IllegalArgumentException error) {
            throw new HttpProxyException("400 Invalid Request Target");
        }
    }

    private boolean isValidDestination(HostPort destination) {
        if (destination.host == null || destination.host.trim().isEmpty() ||
            destination.port < 1 || destination.port > 65_535) {
            return false;
        }
        String host = destination.host.trim().toLowerCase(Locale.US);
        if ("localhost".equals(host) || host.endsWith(".localhost") ||
            "localhost.localdomain".equals(host) || host.endsWith(".local")) {
            return false;
        }
        try {
            for (InetAddress address : resolveAddresses(destination.host, findUpstreamNetwork())) {
                if (isBlockedAddress(address)) {
                    return false;
                }
            }
            return true;
        } catch (IOException error) {
            // Let openUpstream provide the connection-specific failure.
            return true;
        }
    }

    private Socket openUpstream(String host, int port) throws IOException {
        Network network = findUpstreamNetwork();
        InetAddress[] addresses = resolveAddresses(host, network);
        IOException lastError = null;
        for (InetAddress address : addresses) {
            if (isBlockedAddress(address)) {
                continue;
            }
            Socket upstream = new Socket();
            try {
                if (network != null) {
                    network.bindSocket(upstream);
                }
                upstream.connect(new InetSocketAddress(address, port), CONNECT_TIMEOUT_MS);
                return upstream;
            } catch (IOException error) {
                lastError = error;
                closeSocket(upstream);
            }
        }
        throw lastError == null
            ? new IOException("No permitted address was available for the proxy destination.")
            : lastError;
    }

    private InetAddress[] resolveAddresses(String host, Network network) throws IOException {
        try {
            InetAddress literal = InetAddress.getByName(host);
            if (literal.getHostAddress().equals(host) || host.contains(":")) {
                return new InetAddress[] { literal };
            }
        } catch (UnknownHostException ignored) {
            // Resolve below using the selected backhaul.
        }
        // When SafeNet's DNS-only VPN is active, resolve through the system
        // resolver first so its DNS policy can reject blocked hostnames. The
        // resulting socket is still bound to the physical backhaul below;
        // the DNS VPN is not used as a second full-tunnel proxy.
        if (SafeNetDnsVpnService.isRunning()) {
            return InetAddress.getAllByName(host);
        }
        if (network != null) {
            try {
                return network.getAllByName(host);
            } catch (UnknownHostException ignored) {
                // Fall through to the system resolver as a last resort.
            }
        }
        return InetAddress.getAllByName(host);
    }

    private Network findUpstreamNetwork() {
        ConnectivityManager connectivity =
            (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
        if (connectivity == null) {
            return null;
        }
        Network active = connectivity.getActiveNetwork();
        if (isUsableBackhaul(connectivity, active)) {
            return active;
        }
        for (Network network : connectivity.getAllNetworks()) {
            if (isUsableBackhaul(connectivity, network)) {
                return network;
            }
        }
        return null;
    }

    private boolean isUsableBackhaul(ConnectivityManager connectivity, Network network) {
        if (network == null) {
            return false;
        }
        NetworkCapabilities capabilities = connectivity.getNetworkCapabilities(network);
        return capabilities != null &&
            capabilities.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET) &&
            capabilities.hasCapability(NetworkCapabilities.NET_CAPABILITY_NOT_VPN) &&
            !capabilities.hasTransport(NetworkCapabilities.TRANSPORT_VPN) &&
            (capabilities.hasTransport(NetworkCapabilities.TRANSPORT_WIFI) ||
                capabilities.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR) ||
                capabilities.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET));
    }

    private boolean isBlockedAddress(InetAddress address) {
        return address.isAnyLocalAddress() || address.isLoopbackAddress() ||
            address.isLinkLocalAddress() || address.isSiteLocalAddress() ||
            address.isMulticastAddress();
    }

    private void relay(Socket client, Socket upstream) throws IOException {
        client.setSoTimeout(0);
        upstream.setSoTimeout(0);
        executor.execute(() -> copy(upstream, client));
        copy(client, upstream);
    }

    private void copy(Socket source, Socket destination) {
        try {
            byte[] buffer = new byte[16 * 1024];
            int count;
            while ((count = source.getInputStream().read(buffer)) >= 0) {
                destination.getOutputStream().write(buffer, 0, count);
                destination.getOutputStream().flush();
            }
        } catch (IOException ignored) {
            // Closing either side ends the relay.
        } finally {
            closeSocket(source);
            closeSocket(destination);
        }
    }

    private void copyExactly(InputStream input, OutputStream output, int length) throws IOException {
        int remaining = length;
        byte[] buffer = new byte[8192];
        while (remaining > 0) {
            int count = input.read(buffer, 0, Math.min(buffer.length, remaining));
            if (count < 0) {
                throw new IOException("Client closed before the request body completed.");
            }
            output.write(buffer, 0, count);
            remaining -= count;
        }
    }

    private String readLine(InputStream input) throws IOException {
        StringBuilder line = new StringBuilder();
        int previous = -1;
        int current;
        while ((current = input.read()) >= 0) {
            line.append((char) current);
            if (line.length() > MAX_HEADER_BYTES) {
                throw new IOException("Proxy header is too large.");
            }
            if (current == '\n' && previous == '\r') {
                line.setLength(line.length() - 2);
                return line.toString();
            }
            previous = current;
        }
        return line.length() == 0 ? null : line.toString();
    }

    private int readByte(InputStream input) throws IOException {
        return input.read();
    }

    private int readUnsignedShort(InputStream input) throws IOException {
        int high = readByte(input);
        int low = readByte(input);
        if (high < 0 || low < 0) {
            throw new IOException("Proxy request ended unexpectedly.");
        }
        return (high << 8) | low;
    }

    private byte[] readBytes(InputStream input, int length) throws IOException {
        byte[] result = new byte[length];
        int offset = 0;
        while (offset < length) {
            int count = input.read(result, offset, length - offset);
            if (count < 0) {
                throw new IOException("Proxy request ended unexpectedly.");
            }
            offset += count;
        }
        return result;
    }

    private String readNullTerminated(InputStream input, int maxLength) throws IOException {
        byte[] value = new byte[maxLength];
        int index = 0;
        int next;
        while ((next = input.read()) >= 0) {
            if (next == 0) {
                return new String(value, 0, index, StandardCharsets.ISO_8859_1);
            }
            if (index == maxLength) {
                throw new IOException("SOCKS identity is too long.");
            }
            value[index++] = (byte) next;
        }
        throw new IOException("Proxy request ended unexpectedly.");
    }

    private HostPort parseHostPort(String value, int defaultPort) {
        String candidate = value == null ? "" : value.trim();
        if (candidate.startsWith("[")) {
            int closing = candidate.indexOf(']');
            if (closing <= 1) {
                throw new HttpProxyException("400 Invalid Host");
            }
            String host = candidate.substring(1, closing);
            int port = defaultPort;
            if (closing + 1 < candidate.length()) {
                if (candidate.charAt(closing + 1) != ':') {
                    throw new HttpProxyException("400 Invalid Host");
                }
                port = parsePort(candidate.substring(closing + 2));
            }
            return new HostPort(host, port);
        }
        int separator = candidate.lastIndexOf(':');
        if (separator > 0 && candidate.indexOf(':') == separator) {
            return new HostPort(candidate.substring(0, separator), parsePort(candidate.substring(separator + 1)));
        }
        return new HostPort(candidate, defaultPort);
    }

    private int parsePort(String value) {
        try {
            int port = Integer.parseInt(value);
            if (port < 1 || port > 65_535) {
                throw new NumberFormatException();
            }
            return port;
        } catch (NumberFormatException error) {
            throw new HttpProxyException("400 Invalid Port");
        }
    }

    private String formatHostPort(HostPort destination) {
        return destination.host.contains(":")
            ? "[" + destination.host + "]:" + destination.port
            : destination.host + ":" + destination.port;
    }

    private void writeHttpError(Socket client, String status) throws IOException {
        String body = "SafeNet Internet Share: " + status;
        String response = "HTTP/1.1 " + status + "\r\n" +
            "Content-Type: text/plain\r\n" +
            "Content-Length: " + body.getBytes(StandardCharsets.ISO_8859_1).length + "\r\n" +
            "Connection: close\r\n\r\n" + body;
        client.getOutputStream().write(response.getBytes(StandardCharsets.ISO_8859_1));
        client.getOutputStream().flush();
    }

    private void closeServer(ServerSocket server) {
        if (server != null) {
            try {
                server.close();
            } catch (IOException ignored) {
                // The accept loop will exit when the descriptor closes.
            }
        }
    }

    private void closeSocket(Socket socket) {
        if (socket != null) {
            try {
                socket.close();
            } catch (IOException ignored) {
                // Cleanup is best effort.
            }
        }
    }

    private static final class Header {
        final String name;
        final String value;

        Header(String name, String value) {
            this.name = name;
            this.value = value;
        }
    }

    private static final class HostPort {
        final String host;
        final int port;

        HostPort(String host, int port) {
            this.host = host;
            this.port = port;
        }
    }

    private static final class HttpProxyException extends IllegalArgumentException {
        final String status;

        HttpProxyException(String status) {
            this.status = status;
        }
    }
}